def branch = "main"
def repo = "https://github.com/mahesaj/store"
def cred = "ssh"
def dir = "~/"
def server = "mahesajihanfadhlurrahman@34.125.161.74"

pipeline {
    agent any
    stages {
        stage('Pull From Repository') {
            steps {
                sshagent([cred]) {
                    sh """ssh -o StrictHostKeyChecking=no ${server} << EOF
                        cd ${dir}
                        git remote add origin ${repo} || git remote set-url origin ${repo}
                        git pull origin ${branch}
                        exit
                        EOF
                    """
                }
            }
        }

        stage('Docker Compose UP') {
            steps {
                sshagent([cred]) {
                    sh """ssh -o StrictHostKeyChecking=no ${server} << EOF
                        cd ~/store/dist/docker-compose/
                        sudo su mahesa
                        docker compose up -d
                        exit
                        EOF
                    """
                }
            }
        }
    }
}
